### ISSUE TITLE
Error on Conversion

### ISSUE THREAD

**Issue by fr8nki3** [seanap/auto-m4b#58]
2024-07-27 21:38:09 Starting Conversion
2024-07-27 21:38:09 an error occured, that has not been caught:
2024-07-27 21:38:09 Array
2024-07-27 21:38:09 (
2024-07-27 21:38:09     [type] => 1
2024-07-27 21:38:09     [message] => Uncaught ValueError: Path cannot be empty in phar:///usr/local/bin/m4b-tool/src/library/M4bTool/Command/AbstractCommand.php:228
2024-07-27 21:38:09 Stack trace:
2024-07-27 21:38:09 #0 phar:///usr/local/bin/m4b-tool/src/library/M4bTool/Command/AbstractCommand.php(228): file_put_contents()
2024-07-27 21:38:09 #1 phar:///usr/local/bin/m4b-tool/src/library/M4bTool/Command/AbstractCommand.php(462): M4bTool\Command\AbstractCommand->log()
2024-07-27 21:38:09 #2 phar:///usr/local/bin/m4b-tool/src/library/M4bTool/Command/MergeCommand.php(197): M4bTool\Command\AbstractCommand->error()
2024-07-27 21:38:09 #3 phar:///usr/local/bin/m4b-tool/vendor/symfony/console/Command/Command.php(255): M4bTool\Command\MergeCommand->execute()
2024-07-27 21:38:09 #4 phar:///usr/local/bin/m4b-tool/vendor/symfony/console/Application.php(908): Symfony\Component\Console\Command\Command->run()
2024-07-27 21:38:09 #5 phar:///usr/local/bin/m4b-tool/vendor/symfony/console/Application.php(269): Symfony\Component\Console\Application->doRunCommand()
2024-07-27 21:38:09 #6 phar:///usr/local/bin/m4b-tool/vendor/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun()
2024-07-27 21:38:09 #7 phar:///usr/local/bin/m4b-tool/bin/m4b-tool.php(32): Symfony\Component\Console\Application->run()
2024-07-27 21:38:09 #8 /usr/local/bin/m4b-tool(10): require('...')
2024-07-27 21:38:09 #9 {main}
2024-07-27 21:38:09   thrown
2024-07-27 21:38:09     [file] => phar:///usr/local/bin/m4b-tool/src/library/M4bTool/Command/AbstractCommand.php
2024-07-27 21:38:09     [line] => 228
2024-07-27 21:38:09 )
2024-07-27 21:38:09 Finished Converting
2024-07-27 21:38:09 Putting the m4b into a folder
2024-07-27 21:38:09 Deleting duplicate mp3 audiobook folder
2024-07-27 21:38:09 Making a backup of the whole /temp/recentlyadded/
2024-07-27 21:38:09 Making sure all books are in their own folder
2024-07-27 21:38:09 Flattening nested subfolders 3 levels deep or more and renaming files...
2024-07-27 21:38:09 Moving folders with 2 or more audiofiles to /temp/merge/ 
2024-07-27 21:38:09 Moving single file mp3's to /temp/merge/ 
2024-07-27 21:38:09 Moving all the single m4b books to /temp/untagged/ 
2024-07-27 21:38:09 supervise/
2024-07-27 21:38:09 Folder Detected
2024-07-27 21:38:09 Sampling
2024-07-27 21:38:09 Bitrate =
2024-07-27 21:38:09 The folder supervise will be merged to /temp/untagged/supervise/supervise.m4b
2024-07-27 21:38:09 Starting Conversion
2024-07-27 21:38:09 an error occured, that has not been caught:

**Comment by sethglazier** [comment]
@fr8nki3 Did you ever figure this out?

**Comment by ivanvmoreno** [comment]
Can replicate this on latest release.

To debug the reason for the exception, take a look at `<mounted_config_dir>/auto-m4b-tool.log`

In my case, it was a directory ownership problem. Make sure to set the mounted `/temp` directory ownership to the same `UID` and `GID` you're running the container with.
